#!/bin/sh
# Copyright 2025 Rafał Wabik (IceG) - From eko.one.pl forum
# Licensed to the GNU General Public License v3.0.

chmod +x /usr/sbin/qfirehose-start 2>&1 &
chmod +x /usr/sbin/qfirehose-status 2>&1 &
mkdir -p /var/log/qfirehose 2>&1 &
chmod 755 /var/log/qfirehose 2>&1 &
chmod +x /var/log/qfirehose 2>&1 &
mkdir -p /tmp/qfirehoseupload 2>&1 &
exit 0
