name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        run: |
          sudo rm -rf /usr/lib/{jvm,llvm} /usr/local /usr/src/* /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm} /usr/libexec/gcc/x86_64-linux-gnu/14 /usr/lib/x86_64-linux-gnu/{*clang*,*LLVM*} /home/linuxbrew

      - name: Build Packages
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_ci
          PACKAGES: airplay2 ddns-go luci-app-adguardhome luci-app-airplay2 luci-app-argon-config luci-app-chatgpt-web luci-app-ddns-go luci-app-kucat-config luci-app-lucky luci-app-mentohust luci-app-mosdns luci-app-netwizard luci-app-oaf luci-app-openlist luci-app-partexp luci-app-ramfree luci-app-socat luci-app-webdav luci-theme-argon luci-theme-kucat lucky mentohust mosdns oaf open-app-filter openlist v2dat luci-theme-alpha luci-app-diskman luci-app-qbittorrent qbittorrent qt6base qt6tools rblibtorrent smartdns luci-app-smartdns luci-app-unblockneteasemusic
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Organize Files
        run: |
          tar -czf ${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/packages_ci .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: ${{ matrix.arch }}.tar.gz

      - name: Upload Firmware To Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          allowUpdates: true
          tag: ${{ matrix.tag }}-${{ matrix.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
            ${{ matrix.arch }}.tar.gz
